import type { Module } from '../types'

const m: Module = {
  id: 'mlops-l0-linux-networking',
  subjectId: 'mlops',
  level: 0,
  title: 'Linux & Networking Essentials for ML Engineers',
  whyItMatters:
    'Every training box, every container, every CI runner and every production server you will ever touch is a Linux machine you reach over SSH. The gap between "the model works" and "the model is serving traffic" is almost entirely this module: read a permission bit, kill a process without corrupting a checkpoint, rank the top 5 errors out of a 2 GB log, and know within ninety seconds whether an unreachable service is your code, your bind address, or a firewall rule.',
  estMinutes: 50,
  sections: [
    {
      type: 'intuition',
      title: 'One tree. That is the whole filesystem.',
      md: `Windows gives you C:, D:, E: — separate worlds. Linux gives you **one** tree, and everything is hung somewhere on it: a second disk, a USB stick, a network share, even the kernel itself.

- The root is \`/\`. Nothing lives above it. Every absolute path starts there.
- **\`/etc\`** — configuration. Plain text files you can read and edit: \`/etc/hostname\`, \`/etc/nginx/nginx.conf\`, \`/etc/ssh/sshd_config\`.
- **\`/var\`** — things that *grow*: \`/var/log\` (logs), caches, spools. This is the directory that fills your disk.
- **\`/tmp\`** — scratch space, wiped on reboot. Write your throwaway files here, never your checkpoints.
- **\`/home/<you>\`** — your stuff. \`~\` is a shortcut for it.
- **\`/usr/bin\`** — the installed programs. \`which python3\` tells you which file actually runs.
- **\`/proc\`** — not a real disk at all. The kernel pretending to be files, so you can \`cat\` the CPU, the memory, and every running process.`,
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'A tour, and the difference between absolute and relative',
      code: `ls /                       # every path on the machine hangs off this one root
# bin boot dev etc home lib proc root tmp usr var

cat /etc/hostname          # /etc  = configuration, plain text, editable
tail -f /var/log/syslog    # /var  = things that GROW. logs live here
ls /tmp                    # /tmp  = scratch, wiped on reboot
ls /home/rauna             # /home = your files. "~" means exactly this
which python3              # /usr/bin/python3 - the file that actually runs
cat /proc/cpuinfo          # /proc = the kernel, pretending to be files
cat /proc/4417/status      # even a running process is readable as text

pwd                        # where am I right now: /home/rauna/train
ls -lh data/               # RELATIVE: resolves to /home/rauna/train/data
ls -lh /var/log            # ABSOLUTE: starts with / , means the same everywhere
cd ..                      # up one level
cd -                       # jump back to the previous directory`,
      annotations: {
        1: 'No C: or D:. A second disk, an S3-backed mount, a network share - all of them get "mounted" at some directory in this single tree.',
        4: 'The rule that makes Linux debuggable: configuration is text. You can cat it, grep it, diff it, and put it in git.',
        5: 'tail -f follows the file as new lines are written. This is how you watch a service boot, or a training run, in real time.',
        9: 'Nothing here is on disk. /proc/cpuinfo, /proc/meminfo, /proc/<pid>/status are generated by the kernel the instant you read them.',
        12: 'Relative paths depend on where you are standing. In a cron job or a systemd unit you are NOT standing where you think - that is why half of "works on my machine" bugs are relative paths.',
        13: 'Absolute paths mean the same thing from anywhere. In scripts, config files and Dockerfiles, prefer them.',
      },
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'Moving files, and the pager you get at 3am',
      code: `mkdir -p runs/2026-08-20/checkpoints   # -p: create parents, no error if it exists
cp -r data/raw runs/2026-08-20/        # -r to copy a whole directory
mv model.pt runs/2026-08-20/best.pt    # rename and move are the same operation
rm -rf runs/old                        # no trash can, no undo, no confirmation

df -h                                  # WHICH filesystem is full, and how full
# Filesystem      Size  Used Avail Use% Mounted on
# /dev/root        50G   50G     0 100% /
du -sh /var/* 2>/dev/null | sort -h | tail -5   # then: WHO ate it
find /var/log -type f -size +500M      # the usual answer: one unrotated log file
find . -name '*.ckpt' -mtime +7 -delete   # checkpoints older than 7 days, gone`,
      annotations: {
        1: 'mkdir -p is idempotent - safe to run in a script that may run twice. Plain mkdir errors out if the directory already exists.',
        4: 'The most dangerous three characters in this module. rm -rf deletes recursively and silently. Type the path, then read it once more BEFORE pressing Enter. A stray space in "rm -rf / home/rauna/old" deletes the machine.',
        6: 'The 3am order of operations: df -h first. It tells you which mount point is at 100%, which is often not the one you assumed.',
        9: 'du -sh summarises a directory total in human units. Piping through "sort -h" sorts those human units correctly (500M before 2G).',
        10: 'Almost every "disk full" incident is a log that nobody rotated, a pip/conda cache, or a checkpoint directory. Look there first.',
        11: 'find is your batch tool: match by name, size or age, then act. Run it WITHOUT -delete first and read the list.',
      },
    },
    {
      type: 'intuition',
      title: 'Permissions: three questions, asked three times',
      md: `A shared office. Every file asks the same three questions — of you, of your team, of everyone else.

- The three permissions are **r** (read), **w** (write), **x** (execute). For a *directory*, \`x\` means "may enter it".
- The three audiences are **user** (the owner), **group**, **other** (everybody else).
- So every file carries 3 × 3 = nine bits, always printed in that fixed order: \`rwx\` \`rwx\` \`rwx\`.
- A file is not executable because it ends in \`.sh\` or has a \`#!\` line. It is executable because the \`x\` bit is on. Nothing else.
- That is the entire reason a fresh script answers \`Permission denied\` until you \`chmod +x\` it.`,
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'Reading ls -l one character at a time',
      code: `ls -l deploy.sh
# -rwxr-x---  1 rauna mlteam  482 Aug 20 09:14 deploy.sh
# ^ ^  ^  ^
# | |  |  +-- other:  ---   nobody else may even read it
# | |  +----- group mlteam: r-x   read + execute, cannot edit
# | +-------- user rauna:   rwx   read + write + execute
# +---------- type: - regular file, d directory, l symlink

./deploy.sh
# bash: ./deploy.sh: Permission denied      <- the x bit is missing
chmod +x deploy.sh            # add execute for user, group AND other
chmod u+x deploy.sh           # add execute for the OWNER only
chmod 755 deploy.sh           # rwx r-x r-x   (7 = 4+2+1, 5 = 4+0+1)
chmod 644 notes.md            # rw- r-- r--   the sane default for a data file
chmod 600 ~/.ssh/id_ed25519   # rw- --- ---   ssh refuses a key others can read
chown rauna:mlteam deploy.sh  # change owner:group - needs root (sudo)`,
      annotations: {
        2: 'Ten characters, then link count, then OWNER, then GROUP, then size in bytes, then modification time, then the name. Read them in that order every time.',
        7: 'The very first character is the file TYPE, not a permission. "d" for a directory, "l" for a symlink, "-" for an ordinary file. People misread this constantly.',
        10: 'Permission denied on your own script means the x bit, ninety percent of the time. The other ten percent: the script is on a filesystem mounted noexec, or a directory above it lacks x so you cannot even enter.',
        13: 'The octal arithmetic: r=4, w=2, x=1, add them per audience. 7=4+2+1=rwx, 6=4+2=rw-, 5=4+1=r-x, 4=r--, 0=none. 755 = "I can change it, everyone can run it" - the standard for scripts and directories.',
        15: 'Not a suggestion. OpenSSH REFUSES to use a private key that group or other can read, with "UNPROTECTED PRIVATE KEY FILE". 600 on the key, 700 on ~/.ssh.',
        16: 'chown changes WHO owns it, chmod changes what the owner/group/other may DO. Changing ownership away from yourself needs root; you cannot give your files away.',
      },
    },
    {
      type: 'intuition',
      title: 'SSH keys: the padlock you hand out, the key you never do',
      md: `You mail an open padlock to a server. The server clips it to its gate. Only your key opens that padlock — and the key never left your pocket.

- \`ssh-keygen\` makes a **pair**: \`id_ed25519\` (private) and \`id_ed25519.pub\` (public).
- The **public** half is safe to paste anywhere — GitHub, a wiki, a Slack message. It is the padlock.
- The **private** half never leaves your laptop. Not into git, not into a Docker image, not into a CI variable that prints logs.
- On the server, the public key goes into \`~/.ssh/authorized_keys\` — one key per line. That file *is* the access list.
- Login is a challenge: the server encrypts a nonce with your public key; only the matching private key can answer. **The secret is never transmitted.**
- Why this beats passwords: a password can be guessed, phished, brute-forced by bots that scan port 22 all day, and reused across services. A key cannot be typed, cannot be reused by mistake, and revoking one person is deleting one line.`,
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'The full key dance, both machines',
      code: `# ON YOUR LAPTOP - generate the pair once, reuse it forever
ssh-keygen -t ed25519 -C "rauna@laptop"
# Generating public/private ed25519 key pair.
# Enter file in which to save the key (/home/rauna/.ssh/id_ed25519):
# Enter passphrase (empty for no passphrase):
ls ~/.ssh
# id_ed25519       <- PRIVATE. never leaves this machine. never in git.
# id_ed25519.pub   <- PUBLIC. safe to paste anywhere.

# push the PUBLIC half to the server - one command does the whole dance
ssh-copy-id -i ~/.ssh/id_ed25519.pub rauna@10.0.3.7

# what that actually did, over on the server:
cat ~/.ssh/authorized_keys
# ssh-ed25519 AAAAC3NzaC1lZDI1...KpQ rauna@laptop
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys

ssh rauna@10.0.3.7                           # no password prompt any more
ssh -i ~/.ssh/id_ed25519 -v rauna@10.0.3.7   # -v prints WHICH key it offered`,
      annotations: {
        2: 'ed25519 over RSA: shorter, faster, and no key-size argument to get wrong. The passphrase encrypts the key file itself - so a stolen laptop is still not a stolen key. ssh-agent then types it for you once per session.',
        7: 'If you only remember one line from this module: the file without ".pub" never moves. Leaked private keys are one of the most common real-world breaches, and they usually leak via a git commit.',
        11: 'ssh-copy-id appends the public key to authorized_keys on the server, creates ~/.ssh if needed, and fixes the permissions. Doing it by hand is a cat and a chmod - and forgetting the chmod is why it silently keeps asking for a password.',
        14: 'One public key per line. Onboarding a teammate is adding a line; offboarding is deleting one. That is the whole access-control model.',
        16: 'sshd ignores authorized_keys if the file or its directory is group/other writable - and it tells you nothing, it just falls back to the password prompt. Check this first when key auth "does not work".',
        19: '-v is the diagnostic. It shows the key files it tried in order, so you can see it offering the wrong one before you start editing server config.',
      },
    },
    {
      type: 'intuition',
      title: 'Processes: what is running, and how to stop it politely',
      md: `A process is a running program with its own memory, its own PID (process id), and its own exit code when it finishes.

- \`ps aux\` — a snapshot of everything running. \`top\` / \`htop\` — the same thing, live.
- Columns worth knowing: **PID** (the handle you kill), **%CPU**, **%MEM**, **RSS** (actual RAM in use — the honest number), **STAT** (R running, S sleeping, D stuck in I/O, Z zombie), **TIME** (total CPU consumed), **COMMAND**.
- \`kill PID\` sends **SIGTERM** — "please stop". The process catches it, flushes its file, closes the database connection, saves the checkpoint, exits.
- \`kill -9 PID\` sends **SIGKILL** — the kernel deletes it mid-instruction. **SIGKILL cannot be caught**, so nothing is flushed: half-written checkpoints, corrupted SQLite files, locks never released.
- So: always \`kill\` first, wait a few seconds, and only then \`kill -9\`. The same rule is why Docker and Kubernetes send SIGTERM and wait a grace period before SIGKILL.
- Every process ends with an **exit code**: \`0\` means success, anything else is failure. \`137\` = 128 + 9 = it was SIGKILLed, which in a container almost always means the out-of-memory killer.`,
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'Finding it, stopping it, and keeping it alive after you log out',
      code: `ps aux | head -3
# USER    PID %CPU %MEM   VSZ   RSS TTY   STAT START   TIME COMMAND
# rauna  4417 99.8 12.3  9.2G  2.0G pts/0 R+   09:14  12:31 python train.py
top                     # live view; press M to sort by memory, q to quit
htop                    # the same, but readable and arrow-key driven

kill 4417               # SIGTERM (15): "please stop" - the process CAN clean up
kill -9 4417            # SIGKILL (9): removed mid-instruction. Nothing is flushed.
pkill -f train.py       # match on the command line instead of hunting for a PID

python train.py &                          # background - but dies with the shell
nohup python train.py > train.log 2>&1 &   # survives logout, output to a file
tmux new -s train       # what you ACTUALLY use for a 14-hour training run
# ...start the job, press Ctrl-b then d to detach, go home, then reconnect:
tmux attach -t train

python train.py; echo "exit code: $?"
# exit code: 0    <- 0 is success, anything else is failure. 137 = killed (OOM).`,
      annotations: {
        2: 'VSZ is virtual memory - address space the process reserved, mostly meaningless. RSS is resident memory - the pages actually in RAM. When someone asks "how much memory does it use", they mean RSS.',
        3: 'STAT R+ means running in the foreground. D means uninterruptible sleep, stuck waiting on disk or network - a D-state process will not even die from kill -9 until the I/O returns.',
        7: 'Default signal, and the correct first attempt. Python turns SIGTERM into a normal exception path if you install a handler, which is how you make a training loop save its checkpoint before exiting.',
        8: 'The reason a hard kill corrupts state: the process never runs another line, so buffered writes stay in memory, the checkpoint file is half a tensor, and the lock file is still there next boot. Use it only after SIGTERM has clearly failed.',
        11: '& backgrounds the job in THIS shell. When the SSH session drops, the shell dies, the job gets SIGHUP and dies with it. This is why your overnight run was gone in the morning.',
        12: 'nohup ignores SIGHUP so the job outlives the shell, and the redirect gives its output somewhere to go. Good for fire-and-forget - but you cannot get back in to look at it.',
        13: 'tmux (or screen) is the real answer: the session lives on the SERVER. Detach, close the laptop, reconnect from anywhere and your scrollback and running job are exactly as you left them.',
        17: '$? holds the exit code of the last command. This is what CI, Makefiles and "&&" all read - a script that fails but exits 0 is a broken pipeline that reports success.',
      },
    },
    {
      type: 'intuition',
      title: 'grep finds lines, awk cuts columns, sed rewrites text',
      md: `Three tools, three jobs. Keep them separate in your head and you will never reach for the wrong one.

- **grep** — *which lines do I care about?* Pattern in, matching lines out.
- **awk** — *which column of those lines?* It splits every line on whitespace into \`$1 $2 $3…\` and lets you print or filter on them.
- **sed** — *change this text into that text.* Overwhelmingly one job in practice: \`s/old/new/g\`.
- The flags you will actually use on grep: \`-r\` recurse into directories, \`-i\` ignore case, \`-n\` show line numbers, \`-v\` invert (lines that do **not** match), \`-c\` count.
- \`-v\` is the underrated one: \`grep -v DEBUG app.log\` is how you read a log written by an over-enthusiastic developer.`,
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'The trio, with the flags that matter',
      code: `grep -rn "CUDA out of memory" logs/   # -r recurse into the tree, -n line numbers
grep -i error app.log                 # -i case-insensitive: Error, ERROR, error
grep -v DEBUG app.log                 # -v INVERTS: every line that does NOT match
grep -c ERROR app.log                 # -c just the count

awk '{print $3}' access.log           # field 3, split on whitespace ($0 = whole line)
awk -F',' '{print $2, $5}' preds.csv  # -F sets the separator, so this reads CSV
awk '$9 >= 500 {print $7}' access.log # pattern THEN action: filter and project at once

sed 's/localhost/api.internal/g' config.yaml   # substitute, print result to stdout
sed -i.bak 's/DEBUG/INFO/g' logging.conf       # -i edits IN PLACE, .bak keeps a copy`,
      annotations: {
        1: 'The single most-used command on a production box. grep -rn over a log directory is how you find the first occurrence of a failure and the exact file and line it came from.',
        3: 'Noise reduction. Chain them: grep -v DEBUG app.log | grep -v healthz strips both the debug spam and the health-check requests before you read anything.',
        6: 'awk splits on runs of whitespace automatically, so log lines need no parsing. $0 is the whole line, $1 the first field, NF the number of fields, $NF the LAST field.',
        8: 'The form nobody teaches: "pattern { action }". Here: only lines whose 9th field (the nginx status code) is 500 or more, and print only the 7th (the URL path).',
        10: 'sed prints to stdout and leaves the file alone - always run it this way first and eyeball the output.',
        11: '-i rewrites the file itself. Always with a suffix (-i.bak) until you trust the expression, because the un-backed-up version is unrecoverable.',
      },
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'The one pipeline worth memorising',
      code: `# "which errors are hurting us most?" - one line, read it LEFT to RIGHT
grep ERROR app.log | awk '{print $5}' | sort | uniq -c | sort -rn | head -5
#    412 TimeoutError
#    117 ConnectionResetError
#     23 KeyError
#      4 CudaOutOfMemoryError

# same shape on an nginx access log: which endpoints are 5xx-ing?
awk '$9 ~ /^5/ {print $7}' access.log | sort | uniq -c | sort -rn | head

python train.py > out.log       # stdout into a file (truncates the file first)
python train.py >> out.log      # APPEND instead of truncating
python train.py > out.log 2>&1  # stdout to the file, then stderr to that same place
python train.py 2> /dev/null    # throw errors away - /dev/null is the bin
python train.py | tee out.log   # screen AND file at the same time`,
      annotations: {
        2: 'Six stages, each one line-oriented, each dumb on its own: keep the error lines, take field 5 (the error class), group identical values next to each other, collapse each group into a count, sort those counts biggest first, show the top 5.',
        3: 'You can now read a 2 GB log without opening it. This single pipeline shape answers "what is failing most", "which endpoint is slowest", "which user hit us hardest" - only the grep and the field number change.',
        9: '~ /^5/ is "matches the regex: starts with 5". A ranked list of your 5xx endpoints, from a raw access log, in one line.',
        11: '> truncates. Redirecting into a log you wanted to keep is a classic self-inflicted data loss - use >> when in doubt.',
        13: 'ORDER MATTERS. "> out.log 2>&1" means: point stdout at the file, then point stderr wherever stdout now goes. Written the other way round ("2>&1 > out.log"), stderr goes to the terminal and only stdout reaches the file.',
        14: '/dev/null discards everything written to it. "2> /dev/null" hides errors - useful to silence permission noise from find, dangerous everywhere else.',
        15: 'tee is what you want for a long run: watch it live AND keep the transcript. Add -a to append rather than truncate.',
      },
    },
    {
      type: 'note',
      md: '`uniq -c` only collapses **adjacent** duplicate lines — that is why `sort` must come before it, always. And the second `sort -rn` is numeric (`-n`) and reversed (`-r`), because a plain sort would order the counts as text and put "412" before "9".',
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'Environment variables and PATH',
      code: `echo $HOME                   # /home/rauna
echo $PATH                   # /usr/local/bin:/usr/bin:/bin:/home/rauna/.local/bin

export MODEL_DIR=/mnt/models # set for THIS shell and every process it starts
env | sort | head            # the whole environment, as a child process will see it

which python                 # /home/rauna/venv/bin/python  <- FIRST match on PATH
# "command not found" means one of two things: not on PATH, or not executable
export PATH="$HOME/.local/bin:$PATH"   # prepend, so your copy beats the system one

echo 'export MODEL_DIR=/mnt/models' >> ~/.bashrc   # make it stick in future shells
# secrets never go in .bashrc and never go in git - inject them at run time
docker run -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" myimage`,
      annotations: {
        2: 'PATH is an ordered, colon-separated list of directories. The shell walks it left to right and runs the FIRST executable it finds with your name. That is the whole mechanism.',
        4: 'Without export the variable exists only in this shell; child processes never see it. This is the difference between "VAR=x" and "export VAR=x", and it breaks scripts constantly.',
        7: 'The one-command answer to "which python is actually running". Activating a virtualenv is nothing magical - it just puts its bin/ directory at the front of PATH.',
        9: 'Prepend to override, append to provide a fallback. Note the "$PATH" at the end: leave it out and you have just deleted every command on the machine for this shell.',
        11: '~/.bashrc runs for each new interactive shell. Non-interactive shells - cron jobs, CI steps, systemd units - do NOT read it, which is why a script that works in your terminal fails from cron with "command not found".',
        13: 'Config in the environment is the 12-factor rule, and it is what lets one image run in dev, staging and prod unchanged. The secret is passed in at run time; it is never baked into the image.',
      },
    },
    {
      type: 'intuition',
      title: 'Networking, just enough: an IP is the building, a port is the door',
      md: `The IP address gets a packet to the machine. The port number decides which program on that machine receives it.

- A server **binds** a port: "packets arriving on 8000, give them to me." One listener per port — a second one gets \`Address already in use\`.
- Known doors: 22 SSH, 80 HTTP, 443 HTTPS, 5432 Postgres, 6379 Redis, 8000/8080 whatever you are building.
- **DNS** turns a name into an IP before anything connects — the resolver asks the root, the TLD, then the authoritative server, and everyone caches the answer until its TTL expires. Full story: the request journey in **Backend L0 — Web Fundamentals**.
- **\`127.0.0.1\` (localhost)** means "this machine only". Packets never touch a network card. **\`0.0.0.0\`** means "every interface I have" — reachable from outside.
- That single distinction is the classic *"it works on my laptop but not in Docker"*: your app bound to 127.0.0.1, and inside a container "this machine" is the container. \`-p 8000:8000\` forwards to the container, and then nothing is listening on an address the outside can reach.
- The fix is one flag: \`uvicorn --host 0.0.0.0\`, \`flask run --host=0.0.0.0\`, \`-b 0.0.0.0:8000\` for gunicorn.`,
    },
    {
      type: 'visual',
      component: 'PointerBoxDiagram',
      props: {
        title: 'One request, failing its way down the stack',
        notice: 'Same curl, four different failures, then the healthy path. Each step names the exact command that proves or clears that layer - work down the list and you cannot skip a cause.',
        leftLabel: 'what the client does',
        rightLabel: 'what the server side is',
        frames: [
          {
            note: 'Layer 1, DNS. The name turned into an IP, so this layer is fine. Proof: getent hosts api.svc, or dig +short api.svc. If DNS were broken you would get "Could not resolve host" - a name problem, not a network problem, and no packet ever left your machine.',
            stack: [{ name: 'curl api.svc:8000', to: 'dns' }],
            heap: [{ id: 'dns', value: 'name -> 10.0.3.7', label: 'resolved' }],
          },
          {
            note: 'Layer 2, TCP. Connection refused, and it came back instantly. Refused means a machine DID answer and said "nothing is listening on that port" - the process is not running or it crashed. On the server: ss -tulpn | grep 8000 prints nothing, ps aux | grep myapp finds nothing, and the log ends with exit 137, the out-of-memory killer.',
            stack: [{ name: 'TCP connect :8000', to: 'p8000', danger: true }],
            heap: [
              { id: 'p8000', value: 'nothing on :8000', label: 'REFUSED', danger: true },
              { id: 'proc', value: 'app process gone', label: 'exit 137' },
            ],
          },
          {
            note: 'Layer 3, the bind address. The app is running now, and curl localhost:8000 works perfectly when you SSH in - but from outside it still refuses. ss -tulpn shows LISTEN 127.0.0.1:8000 instead of 0.0.0.0:8000: the socket is bound to loopback, so it is reachable inside the container and absolutely nowhere else. Fix: bind 0.0.0.0.',
            stack: [{ name: 'TCP connect :8000', to: 'bind', danger: true }],
            heap: [
              { id: 'bind', value: 'LISTEN 127.0.0.1', label: 'loopback', danger: true },
              { id: 'out', value: 'outside: refused', danger: true },
            ],
          },
          {
            note: 'Layer 4, the packet filter. Bound correctly, yet the connection HANGS and eventually times out. Refused is a fast no; a timeout is silence, and silence means something dropped the packet without replying - a security group, a network ACL or ufw. Test it: nc -zv api.svc 8000 succeeds from a box inside the network and hangs from outside. That is an inbound rule, not your code.',
            stack: [{ name: 'TCP connect :8000', to: 'fw', danger: true }],
            heap: [
              { id: 'fw', value: 'firewall: DROP', label: 'silence', danger: true },
              { id: 'app', value: 'LISTEN 0.0.0.0', label: 'healthy' },
            ],
          },
          {
            note: 'The green path. curl -v prints these layers in order: the resolved host, "Trying 10.0.3.7:8000", the request lines marked >, then the response lines marked <, starting with the status. Reading that output top to bottom tells you which of the four failures above you are in - which is why curl -v is the FIRST command you run, not the last.',
            stack: [{ name: 'GET /healthz', to: 'ok' }],
            heap: [
              { id: 'ok', value: 'HTTP/1.1 200 OK', label: '12 ms' },
              { id: 'app', value: 'LISTEN 0.0.0.0', label: 'healthy' },
            ],
          },
        ],
      },
    },
    {
      type: 'code',
      lang: 'bash',
      title: 'The triage toolkit, in the order you run it',
      code: `# 1. does the name resolve?
getent hosts api.internal          # or: dig +short api.internal

# 2. is anything LISTENING, and on which address?
ss -tulpn | grep 8000
# tcp LISTEN 0 128 127.0.0.1:8000 0.0.0.0:* users:(("python",pid=4417,fd=6))
#                  ^^^^^^^^^^^^^^ loopback only - unreachable from outside this box

# 3. can a TCP connection be opened at all?
nc -zv api.internal 8000           # refused = a fast no. hangs = something DROPS it.
telnet api.internal 8000           # the same test, older muscle memory

# 4. what does the application itself say?
curl -v http://api.internal:8000/healthz
# *   Trying 10.0.3.7:8000...
# > GET /healthz HTTP/1.1
# < HTTP/1.1 200 OK
curl -X POST -H 'Content-Type: application/json' \\
     -d '{"text":"hi"}' http://api.internal:8000/v1/predict

ping api.internal      # is the host even up? ICMP is often blocked, so silence proves little`,
      annotations: {
        2: 'Separates "the name is wrong" from "the network is wrong". If this fails, stop - nothing downstream can work, and it is a DNS or /etc/hosts problem.',
        5: 'ss is the modern netstat. -t TCP, -u UDP, -l listening only, -p the owning process, -n numeric ports (no name lookup, so it never hangs). "ss -tulpn" is worth memorising as one word.',
        7: 'The whole module in one line of output. 127.0.0.1:8000 = inside only. 0.0.0.0:8000 = every interface. If this column says 127.0.0.1 and you are debugging from outside, you already have your answer.',
        10: 'nc -z opens a connection and immediately closes it - a pure port test with no application traffic. The distinction it gives you is the valuable part: refused means reached-and-rejected, timeout means never-arrived.',
        14: '-v shows the whole conversation: > lines are what curl sent, < lines are what came back. This is how you check headers, redirects and TLS without a browser.',
        18: '-X sets the method, -H adds a header, -d sends a body (and implies POST). This four-flag combination tests any JSON API from any shell on any box.',
        21: 'ping tests ICMP, which many cloud security groups block by default. A successful ping is informative; a failed ping proves almost nothing about your service.',
      },
    },
    {
      type: 'note',
      md: 'Firewalls, in one idea: **the cloud default is closed**. An AWS security group or GCP firewall rule starts by denying all inbound traffic and you open specific ports to specific sources. On the box itself `ufw` or `iptables` can do the same thing a second time. So when a service is unreachable but the process is up and bound to `0.0.0.0`, the overwhelmingly likely cause is a missing inbound rule — *not* your code. The tell is the failure mode: a firewall that **rejects** gives you `Connection refused`, a firewall that **drops** (the cloud default) gives you a hang and then a timeout.',
    },
    {
      type: 'intuition',
      title: 'Status codes, read as the person on call',
      md: `Once you *have* an HTTP conversation, the status code tells you whose problem it is. That is its real job at 3am.

- **2xx** — fine. **3xx** — go somewhere else (and a redirect loop is a config bug).
- **4xx: your request.** 400 malformed body, 401 no or bad credentials, 403 authenticated but not allowed, 404 wrong path, 413 payload too large, 429 you are being rate limited. Nothing is broken on the server — do not page anyone.
- **5xx: their server.** 500 an unhandled exception in the application code, 503 the service is refusing work (overloaded, or not ready yet).
- **502 Bad Gateway** — the proxy reached out to your app and got nothing or garbage back. The upstream is **down**: the container exited, the model failed to load, the port is wrong.
- **504 Gateway Timeout** — the upstream is **up but too slow**, past the proxy's timeout. Look at a slow query, a cold model, or a hung thread — not at nginx.
- The first fork in the tree, before any of this: *did you get a status code at all?* Connection refused and connection timed out are **not** HTTP — there was no conversation, so the problem is below HTTP entirely, and you go back to the four layers above.`,
    },
    {
      type: 'note',
      md: 'Carry this ladder into every "the service is down" ticket, in order, because each rung eliminates everything below it: **1.** does the name resolve (`getent hosts`) → **2.** is anything listening, and on which address (`ss -tulpn`) → **3.** can a TCP connection open at all (`nc -zv`: refused vs hang) → **4.** what does HTTP say (`curl -v`) → **5.** what does the application log say (`grep -rn ERROR /var/log/...`, then the ranking pipeline). Say this ladder out loud in an interview and you have already answered the question.',
    },
  ],
  quiz: [
    {
      question: '`ls -l` prints `-rw-r--r--` for a file. Who can modify it?',
      options: [
        { text: 'The owner and the group', explanation: 'The group triple here is r--, read only. The w bit is missing for the group.' },
        { text: 'Anyone, because there is no restriction shown', explanation: 'The other triple is r-- as well. Everyone can read; only one audience can write.' },
        {
          text: 'Only the owner',
          explanation: 'Correct. Read it in threes after the leading type character: rw- for the user, r-- for the group, r-- for other. Only the user has w. This is 644, the standard for a data file.',
        },
        { text: 'Nobody, the file is read-only', explanation: 'The first triple is rw-, so the owner can write. The leading "-" is the file TYPE, not a permission.' },
      ],
      correct: 2,
    },
    {
      question: 'You wrote `deploy.sh`, it has a `#!/bin/bash` shebang, and `./deploy.sh` answers `Permission denied`. Most likely fix?',
      options: [
        {
          text: '`chmod +x deploy.sh` — the execute bit is not set',
          explanation: 'Correct. A file is executable because the x bit is on, not because of its extension or its shebang. A freshly created file gets 644, which has no x anywhere.',
        },
        { text: 'Run it with sudo', explanation: 'sudo runs as root, and root would indeed bypass the bit - but you have just used administrator rights to work around a one-character permission problem. Fix the bit.' },
        { text: 'Add `#!/usr/bin/env bash` instead', explanation: 'The shebang decides which interpreter runs the file once it is allowed to run. It has no effect on whether it is allowed to run.' },
        { text: 'Convert the line endings to Unix', explanation: 'Windows line endings do break scripts - but with "bad interpreter: /bin/bash^M", a different error entirely.' },
      ],
      correct: 0,
    },
    {
      question: 'A training job will not stop. Why try `kill` before `kill -9`?',
      options: [
        { text: '`kill -9` needs root, `kill` does not', explanation: 'Both need the same privileges - you can signal your own processes and root can signal any.' },
        {
          text: 'SIGTERM can be caught, so the process flushes buffers and saves state; SIGKILL cannot be caught, so nothing is cleaned up',
          explanation: 'Correct. That is exactly why a hard kill leaves half-written checkpoints, corrupt SQLite files and stale lock files. Docker and Kubernetes follow the same rule: SIGTERM, grace period, then SIGKILL.',
        },
        { text: '`kill -9` is slower to take effect', explanation: 'The opposite - SIGKILL is immediate because the kernel does not wait for the process to agree.' },
        { text: 'There is no difference, it is habit', explanation: 'There is a large difference, and it is the difference between a clean shutdown and a corrupted checkpoint.' },
      ],
      correct: 1,
    },
    {
      question: 'You start a 14-hour training run over SSH from a laptop you will close. What do you use?',
      options: [
        { text: '`python train.py`', explanation: 'The foreground job dies the moment the SSH session drops - which the closed laptop guarantees.' },
        { text: '`python train.py &`', explanation: '& backgrounds it inside the same shell. When the connection dies, the shell dies, the job gets SIGHUP and dies too.' },
        { text: '`nohup python train.py &`', explanation: 'This does survive logout, which is a real improvement. But you cannot get back into it - no live output, no way to type into it, and you should have redirected the output somewhere.' },
        {
          text: '`tmux new -s train`, start the job, detach with Ctrl-b d',
          explanation: 'Correct. The tmux session lives on the SERVER, so the job and its scrollback survive; you reconnect later from anywhere with tmux attach -t train. This is the standard practice for long runs.',
        },
      ],
      correct: 3,
    },
    {
      question: 'Connecting to a service, you get `Connection refused` instantly. What does that rule OUT?',
      options: [
        { text: 'That the process is running', explanation: 'It does suggest the process is not listening - but the question asks what refused rules out, and the strongest signal is elsewhere.' },
        { text: 'That DNS worked', explanation: 'DNS clearly worked: you got as far as a TCP connection attempt, which needs an IP address to attempt it against.' },
        {
          text: 'A firewall silently dropping packets — a drop gives a hang and then a timeout, not an instant refusal',
          explanation: 'Correct. Refused means a machine answered and actively rejected. That is a fast no: the host is reachable and nothing is listening on that port. Silence followed by a timeout is the firewall signature.',
        },
        { text: 'That the port number is wrong', explanation: 'A wrong port is one of the most likely causes of refused, not something it rules out.' },
      ],
      correct: 2,
    },
    {
      question: 'Your API works with `curl localhost:8000` on the host. Inside Docker with `-p 8000:8000` it is unreachable. First suspect?',
      options: [
        {
          text: 'The app bound to 127.0.0.1, which inside a container means the container itself',
          explanation: 'Correct. 127.0.0.1 never leaves the machine, and in a container "the machine" is the container. Docker forwards traffic to the container interface and finds nothing listening there. Fix: --host 0.0.0.0.',
        },
        { text: 'The Docker port mapping is backwards', explanation: 'Worth checking (-p HOST:CONTAINER), but with identical numbers on both sides direction cannot be the bug.' },
        { text: 'The container has no DNS', explanation: 'You are connecting by IP and port here; DNS is not in the path.' },
        { text: 'The image is missing curl', explanation: 'You are running curl from outside the container, so what the image contains does not matter.' },
      ],
      correct: 0,
    },
    {
      question: 'Which command puts BOTH stdout and stderr into `app.log`?',
      options: [
        { text: '`python train.py 2>&1 > app.log`', explanation: 'Order matters. This points stderr at wherever stdout is now (the terminal), and only then sends stdout to the file. Errors end up on screen, not in the log.' },
        {
          text: '`python train.py > app.log 2>&1`',
          explanation: 'Correct. First stdout is pointed at the file, then stderr is pointed at the same destination stdout now has. Read redirections strictly left to right.',
        },
        { text: '`python train.py > app.log > app.err`', explanation: 'Two stdout redirections - the second simply wins. stderr is never touched.' },
        { text: '`python train.py | app.log`', explanation: 'A pipe feeds another PROGRAM. app.log is a file, so this tries to execute it and fails.' },
      ],
      correct: 1,
    },
    {
      question: 'Your app is healthy in the logs, but users get `502 Bad Gateway` from nginx. Where do you look?',
      options: [
        { text: 'The client — 502 is a bad request', explanation: 'Client-side problems are 4xx. 5xx means the server side owns it.' },
        { text: 'The nginx config for a slow-response timeout', explanation: 'That is 504 Gateway Timeout: the upstream answered too slowly. 502 means it did not answer usably at all.' },
        {
          text: 'The upstream application — 502 means the proxy could not get a valid response from it',
          explanation: 'Correct. 502 says the proxy reached out and got nothing or garbage: the container exited, the model failed to load, the worker crashed, or the upstream port in the config is wrong. "Healthy in the logs" often just means you are reading the log of the replica that is still alive.',
        },
        { text: 'DNS, since 502 is a resolution failure', explanation: 'A resolution failure never produces an HTTP status at all - you would get "could not resolve host" with no conversation.' },
      ],
      correct: 2,
    },
  ],
  interviewQuestions: [
    {
      question: 'Read me this line: `-rwxr-x--- 1 rauna mlteam 482 Aug 20 09:14 deploy.sh`. What can each party do?',
      answer:
        'Character one is the TYPE: "-" is a regular file, "d" a directory, "l" a symlink. Then three triples of rwx. User rauna: rwx, read, write, execute. Group mlteam: r-x, they can read and run it but not edit it. Other: ---, nothing at all, they cannot even read it. Then link count 1, owner rauna, group mlteam, size 482 bytes, mtime, name. In octal that is 750, since r=4, w=2, x=1 added per triple. Two details worth adding: on a directory the x bit means "may enter and traverse", so a directory without x is unreadable even if r is set; and permissions on the file are checked after permissions on every directory in the path, which is why a correctly chmod-ed file can still be denied.',
      isCaseBased: false,
    },
    {
      question: 'When do you use 755, 644 and 600, and what does chown change that chmod does not?',
      answer:
        '644 (rw-r--r--) for ordinary data and config files: the owner edits, everyone reads. 755 (rwxr-xr-x) for scripts, binaries and directories: the owner can change it, everyone can run or enter it. 600 (rw-------) for anything secret - SSH private keys, .env files, credential files - and OpenSSH actively refuses a private key that is readable by group or other. The arithmetic behind the digits: r=4, w=2, x=1, summed per audience, so 7=4+2+1, 6=4+2, 5=4+1. chmod changes WHAT may be done; chown changes WHO owns it, in the form chown user:group path. Ownership changes need root, because otherwise you could dump files onto another user and escape your own disk quota. In practice the pairing that matters is: chown the deploy directory to the service account, then chmod it so only that account can write.',
      isCaseBased: false,
    },
    {
      question: 'Explain how SSH key authentication works and why it is preferred over passwords.',
      answer:
        'ssh-keygen produces an asymmetric pair. The public key is copied to the server and appended, one key per line, to ~/.ssh/authorized_keys; the private key stays on the client forever. At login the server issues a challenge that only the holder of the private key can answer, so the secret itself is never transmitted - unlike a password, which crosses the wire (inside TLS, but it still arrives at the server, which means the server can be tricked into keeping it). Keys beat passwords on four counts: they cannot be guessed or brute-forced, and port 22 on any public IP is scanned continuously by bots; they cannot be phished or accidentally reused across services; they enable non-interactive automation, which is how CI deploys; and revocation is deleting one line from one file rather than rotating a shared secret. Operational details interviewers like to hear: encrypt the private key with a passphrase and let ssh-agent hold it, use ed25519, chmod 700 ~/.ssh and 600 the key and authorized_keys - sshd silently ignores that file if it is group-writable and falls back to a password prompt - and set PasswordAuthentication no once keys work.',
      isCaseBased: false,
    },
    {
      question: 'Difference between `kill` and `kill -9`, and why does that matter for a training job?',
      answer:
        'kill sends SIGTERM (15), a request. The process can install a handler, so it flushes open files, closes database connections, releases locks, writes a final checkpoint and exits with a code you chose. kill -9 sends SIGKILL, which the kernel executes directly - it cannot be caught, blocked or ignored, so the process never runs another instruction. For a training job the consequence is concrete: buffered writes are lost, the checkpoint file is a truncated tensor that will not load, a lock file or GPU allocation is left behind, and an in-progress upload to object storage is a partial object. So the discipline is: kill, wait a few seconds, then kill -9 only if it is still there. Two things worth naming: a process stuck in D state, uninterruptible I/O, will not even die from SIGKILL until the I/O returns; and this same pattern is the one Docker and Kubernetes use - SIGTERM, then a terminationGracePeriod, then SIGKILL - which is why a container that ignores SIGTERM gets hard-killed on every deploy and shows up as exit code 137.',
      isCaseBased: false,
    },
    {
      question: 'Case: monitoring says your model API is unreachable. Users get nothing. Walk me through your triage.',
      answer:
        'I go down the stack in order, because each rung eliminates everything below it. (1) DNS: getent hosts api.internal or dig +short. "Could not resolve host" means the name, not the network, and no packet ever left my machine. (2) Transport: nc -zv host 8000, and I read the failure MODE, not just the failure. Connection refused is a fast no - a machine answered and nothing is listening. A hang followed by a timeout is silence - a packet filter dropped it, which means a security group, a network ACL or ufw, not my code. (3) If refused, I get onto the box and run ss -tulpn | grep 8000. Empty output means the process is dead: ps aux | grep, then the logs, then check for exit 137, which is the out-of-memory killer. Output showing 127.0.0.1:8000 instead of 0.0.0.0:8000 means it is bound to loopback - reachable inside the container and nowhere else - and the fix is one flag. (4) If a connection opens, curl -v /healthz and read the status: 502 means the proxy could not get a valid response from the upstream, so the app is down behind it; 504 means the upstream is up but slower than the proxy timeout; 500 is an unhandled exception, so I go to the application log; 403 or 401 means I got all the way through and the problem is credentials. (5) Then the log: grep -rn ERROR over /var/log or docker logs, and the ranking pipeline - grep ERROR | awk to the message field | sort | uniq -c | sort -rn | head - to see whether this is one failure or thousands. Throughout, I check whether ALL replicas are affected or one, because that decides between a code deploy and one sick host. And I say the classification out loud: refused, timeout and a 5xx are three different worlds - refused is nothing listening, timeout is nothing replying, 5xx is the app itself.',
      isCaseBased: true,
    },
    {
      question: 'Case: 3am page. The training box is at 100% disk and jobs are failing. What do you type?',
      answer:
        'df -h first, because it tells me which MOUNT POINT is full - often /var or a data volume rather than /, and the fix differs. Then du -sh /var/* 2>/dev/null | sort -h | tail -5 to walk down into the biggest offender, repeating one level at a time; du without -s on the top level would take forever on a large tree. Then find /var/log -type f -size +500M, because the answer is usually one of four things: an unrotated log, a pip or conda or Docker layer cache, checkpoints nobody deleted, or core dumps. Immediate relief in order of safety: truncate the offending log with : > /var/log/huge.log rather than rm, because deleting a file that a running process still holds open frees nothing until that process restarts - the space stays claimed and df keeps saying 100% while du says the file is gone, which is the classic confusing symptom; then docker system prune for image and layer garbage; then find on old checkpoints with -mtime +7, listed first and only then re-run with -delete. Then the real fix, which is what an interviewer is listening for: configure logrotate, put checkpoints on a separate volume so a runaway job cannot take down the OS, ship old artifacts to object storage, and add a disk-usage alert at 80% so this is a ticket at 3pm instead of a page at 3am.',
      isCaseBased: true,
    },
    {
      question: 'Case: a nightly retraining script runs perfectly when you execute it by hand, but fails every night from cron. Diagnose.',
      answer:
        'This is almost always environment, not logic, and there are four usual causes. (1) PATH: cron runs with a minimal environment, so python resolves to /usr/bin/python instead of your virtualenv and you get "command not found" or the wrong interpreter. Fix by calling the absolute path, /home/rauna/venv/bin/python. (2) Environment variables: cron does not read ~/.bashrc or ~/.profile, so anything you exported there - MODEL_DIR, AWS credentials, CUDA_VISIBLE_DEVICES - simply does not exist. Set them in the crontab or source an env file explicitly at the top of the script. (3) Working directory: cron starts you in the home directory, so every relative path in the script points somewhere else. Use absolute paths, or cd at the top. (4) Permissions and identity: cron runs as a specific user, which may not own the output directory or have the SSH key, so writes and pushes fail. The way I would actually find it, rather than guess: redirect everything to a log - >> /var/log/retrain.log 2>&1 on the cron line, because by default cron mails output nobody reads - then compare "env" from the script under cron against my interactive env. The durable fix is to stop depending on the ambient shell at all: run the job in a container or a systemd unit with an explicit environment, and make the script fail loudly with a non-zero exit code so the failure is visible instead of silent.',
      isCaseBased: true,
    },
    {
      question: 'Write me a command that finds the five most common errors in a large log, and explain each stage.',
      answer:
        'grep ERROR app.log | awk \'{print $5}\' | sort | uniq -c | sort -rn | head -5. Left to right: grep keeps only the error lines, cheaply, so nothing downstream sees the whole file. awk splits each line on whitespace and prints field 5, the error class - that is the projection step, and the field number is the only thing that changes between logs. sort brings identical values next to each other, which is mandatory because uniq only collapses ADJACENT duplicates. uniq -c collapses each run into one line prefixed with its count. sort -rn re-sorts by that count, numerically and descending - numerically matters, because a lexical sort puts "412" before "9". head -5 takes the top of the list. The reason to internalise this shape is that it generalises: swap the grep and the field number and the same six stages answer "which endpoint returns the most 5xx", "which user hit us hardest", "which host is failing". For nginx specifically I would use awk \'$9 ~ /^5/ {print $7}\' access.log piped into the same tail, which filters on the status field and projects the path in one step. And the honest caveat: this is for a box you are logged into. Once you have more than a handful of machines, this pipeline is what your log aggregator does for you.',
      isCaseBased: false,
    },
    {
      question: 'What is the difference between binding to 127.0.0.1 and 0.0.0.0, and why does it break in Docker?',
      answer:
        '127.0.0.1 is the loopback interface: packets addressed to it never reach a network card, so only processes on that same machine can connect. 0.0.0.0 is a wildcard meaning "listen on every interface I have", which includes the ones the outside world can reach. Frameworks default to 127.0.0.1 deliberately, as a safe default for local development. In a container "that same machine" is the container, so an app bound to 127.0.0.1 is reachable only from inside it. docker run -p 8000:8000 forwards host traffic to the container interface - and finds nothing listening there, so you get connection refused even though the process is clearly running and curl works when you exec into the container. The fix is one flag: uvicorn --host 0.0.0.0, gunicorn -b 0.0.0.0:8000, flask run --host=0.0.0.0. Confirm it with ss -tulpn, which prints the bind address explicitly. The security nuance worth saying: 0.0.0.0 does expose the service on every interface, so the thing that keeps it private is the firewall or security group in front, not the bind address.',
      isCaseBased: false,
    },
    {
      question: 'A colleague says "the deploy is broken, I get a 403". Another says "I get a 504". Are these the same incident?',
      answer:
        'Almost certainly not, and the codes say why. 403 Forbidden is 4xx: the request reached the application, was understood, was authenticated, and was refused on authorisation grounds - a missing role, an IAM policy, a bucket policy, an expired token exchanged for a valid-but-underprivileged one. Nothing is broken server-side; I would look at credentials and permissions, and I would not page anyone. 504 Gateway Timeout is 5xx and specifically a proxy-level failure: the gateway forwarded the request upstream and the upstream did not answer within the timeout. That is a slow or hung backend - a cold model load, a slow query, a saturated thread pool, a dependency that is itself timing out. Its sibling 502 Bad Gateway means the upstream returned nothing usable at all, so the process is down or crashed. So: the 403 person has a permissions problem, the 504 person has a capacity or health problem, and treating them as one incident wastes the first twenty minutes. The general triage rule I would state is: 4xx is the request, 5xx is the server, and 502 or 504 specifically means look past the proxy at the upstream - down for 502, slow for 504.',
      isCaseBased: false,
    },
    {
      question: 'What is PATH, how does the shell resolve a command, and how would you debug "command not found" when the binary clearly exists?',
      answer:
        'PATH is an ordered, colon-separated list of directories. When you type a bare command name the shell walks that list left to right and executes the first matching executable file it finds; first match wins, which is exactly how a virtualenv works - activating it just prepends its bin directory. Debugging in order: which -a python shows every match on PATH and their order, so you can see the wrong one winning; echo $PATH shows whether the directory is even in the list; ls -l on the actual file checks the x bit, because a file that is present but not executable is skipped and reported as not found. If the file and the PATH are both fine, the remaining cases are: the shell has cached an old location (hash -r clears it), you are in a different shell or a non-interactive one that never sourced ~/.bashrc - the cron and CI case - or the binary is dynamically linked against a library that is missing, which produces a "not found" message that is really about the loader, and ldd on the binary reveals it. The fix that stops it recurring is to not depend on the ambient shell: absolute paths in scripts and cron entries, and an explicit environment in the container or unit file. And note "command not found" exits with code 127, which is a useful thing to recognise in CI output.',
      isCaseBased: false,
    },
  ],
  flashcards: [
    {
      front: 'The five directories that matter',
      back: '/etc config (text), /var/log logs (the disk filler), /tmp scratch (wiped on reboot), /usr/bin installed programs, /proc the kernel pretending to be files.',
    },
    {
      front: 'Reading ls -l: -rwxr-x---',
      back: 'Char 1 = TYPE (- file, d dir, l link). Then three triples: user rwx, group r-x, other ---. r=4, w=2, x=1 → 750.',
    },
    {
      front: 'chmod 755 / 644 / 600',
      back: '755 rwxr-xr-x scripts and directories. 644 rw-r--r-- data and config. 600 rw------- secrets and SSH private keys (ssh refuses anything looser).',
    },
    {
      front: 'The SSH key model',
      back: 'ssh-keygen makes a pair. Public half → server, appended to ~/.ssh/authorized_keys. Private half never leaves your laptop. The secret is never transmitted — the server challenges, the key answers.',
    },
    {
      front: 'kill vs kill -9',
      back: 'SIGTERM (15) can be caught → flush buffers, save checkpoint, exit cleanly. SIGKILL (9) cannot be caught → nothing is cleaned up, hence corrupt state. Always TERM first. Exit 137 = 128+9 = was SIGKILLed (usually OOM).',
    },
    {
      front: 'Long training run over SSH',
      back: '"&" dies with the shell. nohup survives logout but you cannot get back in. tmux/screen is the answer: the session lives on the server — Ctrl-b d to detach, tmux attach -t train to return.',
    },
    {
      front: 'The log-ranking pipeline',
      back: 'grep ERROR app.log | awk \'{print $5}\' | sort | uniq -c | sort -rn | head -5. sort must precede uniq -c (uniq only collapses ADJACENT lines); sort -rn is numeric so 412 beats 9.',
    },
    {
      front: 'Redirection: > >> 2>&1 /dev/null',
      back: '> truncates, >> appends, 2> is stderr, /dev/null discards. Both streams to a file: cmd > out.log 2>&1 — in that order. Reversed, stderr still goes to the terminal.',
    },
    {
      front: '127.0.0.1 vs 0.0.0.0',
      back: 'Loopback = this machine only (and inside a container, "this machine" is the container). 0.0.0.0 = every interface, reachable from outside. The whole "works locally, not in Docker" bug. Check with ss -tulpn.',
    },
    {
      front: 'Refused vs timeout vs 5xx',
      back: 'Connection refused = fast no, host reached, nothing listening. Timeout/hang = packets dropped, a firewall or security group (the cloud default is closed). 502 = upstream down, 504 = upstream too slow. 4xx = your request, 5xx = their server.',
    },
  ],
  mindmapMarkdown: `- Linux & Networking Essentials
  - Filesystem
    - One tree: /etc config, /var/log logs, /tmp scratch, /proc kernel
    - Absolute vs relative paths (cron and Docker break relative)
    - Disk full at 3am: df -h first, then du -sh | sort -h
    - rm -rf has no undo; find -size / -mtime for batch cleanup
  - Permissions
    - rwx for user / group / other; first ls -l char is the TYPE
    - r=4 w=2 x=1 -> 755 scripts, 644 data, 600 secrets
    - Permission denied -> chmod +x; chown owner:group needs root
  - SSH keys
    - Public half on the server, private never leaves the laptop
    - ~/.ssh/authorized_keys, chmod 700/600; keys beat passwords
  - Processes
    - ps aux, top/htop; RSS is the honest memory number
    - SIGTERM cleans up, SIGKILL -9 does not; exit 137 = OOM kill
    - & dies with the shell, nohup survives, tmux is what you use
  - Text trio and pipes
    - grep -r -i -v -n, awk fields, sed s/old/new/g
    - sort | uniq -c | sort -rn = ranked failures
    - > >> 2>&1 /dev/null tee; PATH first match wins
  - Networking
    - Port = door on an IP, one listener each
    - localhost vs 0.0.0.0 (the Docker trap)
    - DNS name -> IP (see Backend L0 request journey)
    - ss -tulpn, curl -v, nc -zv, ping
    - Refused = fast no; timeout = firewall dropped, cloud default closed
  - HTTP triage
    - 4xx your request, 5xx their server
    - 502 upstream down, 504 upstream slow; no status = below HTTP`,
}

export default m
